### ISSUE TITLE
newer version of mbed

### ISSUE THREAD

**Issue by mburumaxwell** [platformio/builder-framework-mbed#11]
Is there a plan to update the mbed version to a newer one?
I have tried the guidance at [https://community.platformio.org/t/how-to-add-new-version-of-mbed-framework/3200](https://community.platformio.org/t/how-to-add-new-version-of-mbed-framework/3200) but the script fails for mbed 5.10 when generating variants.

**Comment by ivankravets** [comment]
Yes, we are working on the support for mbed 5.10.

**Comment by mburumaxwell** [comment]
Thanks for fixing this. I find it necessary to close the issue
