### ISSUE TITLE
Mbed Build Error - RTOS ‘osKernelGetTickCount’

### ISSUE THREAD

**Issue by GeorgeStephens** [platformio/builder-framework-mbed#8]
This follows on from: [PlatformIO Community](https://community.platformio.org/t/mbed-build-error-rtos-oskernelgettickcount/3925)

When trying to build a project based on mbed and disco_f769ni i get the following error if `<mbed-rtos>` is included in the build. This is using the default mbed platform as downloaded and configured by PlatformIO for vscode. 

'platformio.ini' is:
 `[env:disco_f769ni]
platform = ststm32
board = disco_f769ni
framework = mbed`

Error after clean and build is:
`Compiling .pioenvs\disco_f769ni\libf2e\rtos\TARGET_CORTEX\rtx5\RTX\Source\TOOLCHAIN_GCC\TARGET_RTOS_M4_M7\irq_cm4f.o
Compiling .pioenvs\disco_f769ni\libf2e\rtos\TARGET_CORTEX\rtx5\RTX\Source\rt_OsEventObserver.o
C:\Users\DesktopX6\.platformio\packages\framework-mbed\rtos\Kernel.cpp: In function 'uint64_t rtos::Kernel::get_ms_count()':
C:\Users\DesktopX6\.platformio\packages\framework-mbed\rtos\Kernel.cpp:37:16: error: 'osKernelGetTickCount' was not declared in this scope
if (sizeof osKernelGetTickCount() == sizeof(uint64_t)) {
^~~~~~~~~~~~~~~~~~~~
^~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs\disco_f769ni\libf2e\rtos\TARGET_CORTEX\rtx5\RTX\Source\rtx_delay.o
*** [.pioenvs\disco_f769ni\libf2e\rtos\Kernel.o] Error 1`

I have recreated this on two separate PC's both running PlatformIO for VS-code as well PlatformIO for Atom.

**Comment by valeros** [comment]
You need to enable RTOS module as described on this page [mbed framework configuration](http://docs.platformio.org/en/latest/frameworks/mbed.html#configuration).
